### ISSUE TITLE
minesweeper sucks

### ISSUE THREAD

**Issue by EddieTheEd** [Arcade-Classics/Arcade-Classics#7] opened 2023-03-08 04:02 UTC

**Comment by EddieTheEd** [comment] 2023-03-08 04:03
step 1: play a game of minesweeper above easy difficulty
step 2: in the middle close the extension
step 3: reopen extension

result: upon pressing the resume game button, the minesweeper starts as if it was in easy difficulty. 

please fix this ruined my experience i will be leaving a 2/5 stars on yelp

**Comment by Hugo-Maxted** [comment] 2023-03-08 07:32
Duplicate of #1

**Closed by Hugo-Maxted** 2023-03-08 07:32 UTC
